### ISSUE TITLE
作者你好，最近在学习paging，有幸看见这篇博客，有些疑问希望解答下

### ISSUE THREAD

**Issue by TsaiYongChuan** [idisfkj/android-api-analysis#2]
在NewsAdapter类里面写了个判断刷新状态的方法updateLoadStatus

    fun updateLoadStatus(loadStatus: LoadStatus) {
        val hadLoad = showLoadStatus()
        this.loadStatus = loadStatus
        val hasLoad = showLoadStatus()
        if (hadLoad != hasLoad) {
            if (!hadLoad && hasLoad) {
                notifyItemInserted(super.getItemCount())
            } else {
                notifyItemRemoved(super.getItemCount())
            }
        } else {
            notifyItemChanged(super.getItemCount())
        }
    }

请问这么写是判断是什么，我看了好久没看明白，大概知道是没有数据进行刷新，但不知道为什么要notifyItemRemoved

**Comment by idisfkj** [comment]
上拉加载更多请求已经完成，需要更新底部加载更多的`LOAD_TYPE`类型的视图。

提醒：

1. 可以自行追溯一下`LoadStatus`的来源
2. `getItemCount`方法
3. `getItemViewType`方法
